import 'dart:ui' show Rect;

import 'package:flutter_test/flutter_test.dart';
import 'package:parity/logic/compare.dart';
import 'package:parity/logic/parser.dart';
import 'package:parity/logic/ocr.dart';

/// Regression test for demo_assets/: pins down that the label-panel layout
/// generated by overlay_labels_on_breadboard.ps1 and generate_demo_screens.ps1
/// actually parses into position+component pairs the way the demo README
/// promises, using synthetic OCR blocks at the same coordinates and font
/// scale the generator scripts use. This is the check that would have caught
/// the original "no valid labels found" bug (no P-labels in the raw photo)
/// and the label-merging bug (edge-to-edge boxes on one row) before either
/// reached a real device.
OcrBlock block(
  String text,
  double left,
  double top, {
  double width = 120,
  double height = 90,
}) {
  return OcrBlock(
    text: text,
    boundingBox: Rect.fromLTWH(left, top, width, height),
  );
}

void main() {
  group('demo_spec_realistic.png layout (P1/P2/P3 at x=90/500, y+=200)', () {
    test('parses as three clean rows, no unparsed, no noise', () {
      final blocks = [
        block('P1', 90, 100),
        block('NE555', 500, 100, width: 260),
        block('P2', 90, 300),
        block('LM358', 500, 300, width: 260),
        block('P3', 90, 500),
        block('LM393', 500, 500, width: 260),
      ];
      final result = parseBlocks(blocks);
      expect(result.unparsedRows, isEmpty);
      expect(result.ignoredNoise, isEmpty);
      expect(result.items.map((i) => '${i.position}:${i.component}').toList(), [
        'P1:NE555',
        'P2:LM358',
        'P3:LM393',
      ]);
    });
  });

  group(
    'demo_assembly_realistic_*.png label panel (P1/P2 at x=100/550, y+=180, below a 1024px photo)',
    () {
      test('match scenario parses identically to the spec', () {
        final blocks = [
          block('P1', 100, 1134),
          block('NE555', 550, 1134, width: 260),
          block('P2', 100, 1314),
          block('LM358', 550, 1314, width: 260),
          block('P3', 100, 1494),
          block('LM393', 550, 1494, width: 260),
        ];
        final result = parseBlocks(blocks);
        expect(result.unparsedRows, isEmpty);
        expect(result.items, hasLength(3));

        final spec = parseBlocks([
          block('P1', 90, 100),
          block('NE555', 500, 100, width: 260),
          block('P2', 90, 300),
          block('LM358', 500, 300, width: 260),
          block('P3', 90, 500),
          block('LM393', 500, 500, width: 260),
        ]).items;

        expect(compare(spec, result.items).isMatch, isTrue);
      });

      test(
        'tampered scenario (P2 mismatched, P3 row omitted) produces the documented diff',
        () {
          final tamperedBlocks = [
            block('P1', 100, 1134),
            block('NE555', 550, 1134, width: 260),
            block('P2', 100, 1314),
            block('NE555', 550, 1314, width: 260),
          ];
          final tampered = parseBlocks(tamperedBlocks).items;

          final spec = parseBlocks([
            block('P1', 90, 100),
            block('NE555', 500, 100, width: 260),
            block('P2', 90, 300),
            block('LM358', 500, 300, width: 260),
            block('P3', 90, 500),
            block('LM393', 500, 500, width: 260),
          ]).items;

          final result = compare(spec, tampered);
          expect(result.isMatch, isFalse);
          expect(result.mismatched.single.position, 'P2');
          expect(result.mismatched.single.expected, 'LM358');
          expect(result.mismatched.single.found, 'NE555');
          expect(result.missing.single.position, 'P3');
          expect(result.unexpected, isEmpty);
        },
      );
    },
  );

  test(
    'the ORIGINAL unlabeled breadboard photo (chip text only, no P-labels) parses to nothing',
    () {
      // Reproduces why "no valid labels found" happened: the raw photo's only
      // text is each chip's etched part code, e.g. "NE555P" / "93M" / "DN1810"
      // stacked vertically -- none of it starts with a position label, so every
      // line lands in unparsedRows regardless of how tightly it's cropped.
      final blocks = [
        block('NE555P', 300, 460, width: 180),
        block('93M', 300, 500, width: 90),
        block('DN1810', 300, 540, width: 130),
      ];
      final result = parseBlocks(blocks);
      expect(result.items, isEmpty);
      expect(result.isEmpty, isTrue);
    },
  );
}
